services:

  flux_se.sylius_payum_monetico.action.cancel:
    public: true
    class: FluxSE\SyliusPayumMoneticoPlugin\Action\CancelAction
    tags:
      - { name: payum.action, factory: monetico }

  flux_se.sylius_payum_monetico.action.refund:
    public: true
    class: FluxSE\SyliusPayumMoneticoPlugin\Action\RefundAction
    tags:
      - { name: payum.action, factory: monetico }

  flux_se.sylius_payum_monetico.action.convert_payment:
    public: true
    class: FluxSE\SyliusPayumMoneticoPlugin\Action\ConvertPaymentAction
    arguments:
      $contextProvider: '@flux_se.sylius_payum_monetico.provider.context'
      $referenceProvider: '@flux_se.sylius_payum_monetico.provider.reference'
      $commentProvider: '@flux_se.sylius_payum_monetico.provider.comment'
      $entityManager: '@doctrine.orm.entity_manager'
    tags:
      - { name: payum.action, factory: monetico, prepend: true }
